src/Entity/Fds.php
<?php

namespace App\Entity;

use App\Repository\FdsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: FdsRepository::class)]
class Fds
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $chemin_pdf = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $creer_le = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $supprimer_le = null;

    #[ORM\ManyToOne(inversedBy: 'fds')]
    private ?Produit $produit = null;

   

    public function __construct()
    {
        
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCheminPdf(): ?string
    {
        return $this->chemin_pdf;
    }

    public function setCheminPdf(string $chemin_pdf): static
    {
        $this->chemin_pdf = $chemin_pdf;

        return $this;
    }

    public function getCreerLe(): ?\DateTimeInterface
    {
        return $this->creer_le;
    }

    public function setCreerLe(\DateTimeInterface $creer_le): static
    {
        $this->creer_le = $creer_le;

        return $this;
    }

    public function getSupprimerLe(): ?\DateTimeInterface
    {
        return $this->supprimer_le;
    }

    public function setSupprimerLe(?\DateTimeInterface $supprimer_le): static
    {
        $this->supprimer_le = $supprimer_le;

        return $this;
    }

    /**
     * @return Collection<int, produit>
     */

    public function getProduit(): ?Produit
    {
        return $this->produit;
    }

    public function setProduit(?Produit $produit): static
    {
        $this->produit = $produit;

        return $this;
    }
    
}

src/Form/FdsType.php
<?php

namespace App\Form;

use App\Entity\Fds;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class FdsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('chemin_pdf')
            ->add('creer_le')
            ->add('supprimer_le')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Fds::class,
        ]);
    }
}

templates/fds/_delete_form.html.twig
<form method="post" action="{{ path('app_fds_delete', {'id': fds.id}) }}" onsubmit="return confirm('Voulez vous vraiment supprimer ce fichier');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ fds.id) }}">
    <button class="btn">Delete</button>
</form>

templates/fds/_form.html.twig
{{ form_start(form, {'attr': {'class': 'form'}}) }}
    <div class="mb-3">
        {{ form_widget(form) }}
    </div>
    <div class="mb-3">
        <button class="btn">{{ button_label|default('Save') }}</button>
    </div>
{{ form_end(form) }}

templates/fds/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Fds{% endblock %}

{% block body %}
    <h1 class="animated fadeInLeft">Edit Fds</h1>

    {{ include('fds/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_fds_index') }}">back to list</a>

    {{ include('fds/_delete_form.html.twig') }}
{% endblock %}

templates/fds/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Fds index{% endblock %}

{% block body %}
    <h1 class="animated fadeInLeft">Fds index</h1>

    <table class="table table-striped table-bordered">
        <thead>
            <tr>
                <th>Id</th>
                <th>Chemin_pdf</th>
                <th>Creer_le</th>
                <th>Supprimer_le</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for fd in fds %}
            <tr>
                <td>{{ fd.id }}</td>
                <td>{{ fd.cheminPdf }}</td>
                <td>{{ fd.creerLe ? fd.creerLe|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ fd.supprimerLe ? fd.supprimerLe|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('app_fds_show', {'id': fd.id}) }}" class="btn btn-info">show</a>
                    <a href="{{ path('app_fds_edit', {'id': fd.id}) }}" class="btn btn-warning">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_fds_new') }}">Create new</a>
{% endblock %}

templates/fds/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Fds{% endblock %}

{% block body %}
    <h1 class="animated fadeInLeft">Create new Fds</h1>

    {{ include('fds/_form.html.twig') }}

    <a href="{{ path('app_fds_index') }}">back to list</a>
{% endblock %}

templates/fds/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Fds{% endblock %}

{% block body %}
    <h1 class="animated fadeInLeft">Fds</h1>

    <table class="table table-striped table-bordered">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ fd.id }}</td>
            </tr>
            <tr>
                <th>Chemin_pdf</th>
                <td>{{ fd.cheminPdf }}</td>
            </tr>
            <tr>
                <th>Creer_le</th>
                <td>{{ fd.creerLe ? fd.creerLe|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Supprimer_le</th>
                <td>{{ fd.supprimerLe ? fd.supprimerLe|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_fds_index') }}">back to list</a>

    <a href="{{ path('app_fds_edit', {'id': fd.id}) }}" class="btn btn-warning">edit</a>

    {{ include('fds/_delete_form.html.twig') }}
{% endblock %}